import os

GEOCODING_LOCATIONS_RESPONSE_LIM = 5
OPENWEATHERMAP_API_KEY = os.environ.get('OPENWEATHERMAP_API_KEY')
OPENWEATHERMAP_ONECALLAPI_URL = os.environ.get('OPENWEATHERMAP_ONECALLAPI_URL')
OPENWEATHERMAP_CURRENTWEATHERDATA_API_URL = os.environ.get('OPENWEATHERMAP_CURRENTWEATHERDATA_API_URL')
OPENWEATHERMAP_GEOCODINGAPI_URL = os.environ.get('OPENWEATHERMAP_GEOCODINGAPI_URL')
