# Generated by Django 5.1.3 on 2025-01-11 10:56

import weatherapp.weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='local_names',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
    ]
