# Generated by Django 5.1.3 on 2025-01-12 14:49

import datetime
import weatherapp.weather.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_location_local_names_alter_location_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
        migrations.AlterField(
            model_name='location',
            name='local_names',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddConstraint(
            model_name='userlocation',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='unique_user_location'),
        ),
    ]
