# Generated by Django 5.1.3 on 2025-02-09 10:10

import weatherapp.weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_location_latitude_alter_location_local_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(validators=[weatherapp.weather.models.get_max_min_value_validator]),
        ),
    ]
