# Generated by Django 5.1.6 on 2025-02-24 13:27

import weatherapp.weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_location_country_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
