# Generated by Django 5.1.6 on 2025-02-26 18:23

import weatherapp.weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='local_names',
            field=models.JSONField(blank=True, null=True),
        )
    ]
